services:
  rtvd-strapi:
    container_name: rtvd-strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} 
    ports:
      - "1337:1337"
    depends_on:
      - db
    networks:
      - myproject_network

  db:
    image: postgres
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
    ports:
      - "5432:5432"
    networks:
      - myproject_network

networks:
  myproject_network:
    driver: bridge
